#ifndef _MEMALYZE_COMMON_H
#define _MEMALYZE_COMMON_H

#define IOCTL_MIRROR_CREATE_MIRROR (ULONG) CTL_CODE(FILE_DEVICE_UNKNOWN, 0x00, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_MIRROR_START_MIRROR  (ULONG) CTL_CODE(FILE_DEVICE_UNKNOWN, 0x01, METHOD_NEITHER, FILE_ANY_ACCESS)
#define IOCTL_MIRROR_STOP_MIRROR   (ULONG) CTL_CODE(FILE_DEVICE_UNKNOWN, 0x02, METHOD_NEITHER, FILE_ANY_ACCESS)

#endif
